[tool.poetry]
name = "pyphenotyper"
version = "0.1.1"
description = "NPEC pipeline"
authors = ["Borislav Nachev <220472@buas.nl>",
    "Vlad Bogdan Narcis Matache <224108@buas.nl",
    "Wesley van Gaalen <224682@buas.nl>",
    "Francisco R. Mansilha <220387@buas.nl>",
    "Fedor Chursin <220904@buas.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10.0, <=3.10.14"
tensorflow-io-gcs-filesystem = { version = "0.30.0", markers = "sys_platform == 'linux' or sys_platform == 'win32'" }
tensorflow = { version = "2.10.0", markers = "sys_platform == 'linux' or sys_platform == 'win32'" }
tensorflow-intel = { version = "2.10.0", markers = "sys_platform == 'win32'"}
tensorflow-macos = { version = "2.10.0", markers = "sys_platform == 'darwin'" }
opencv-python = "^4.9.0.80"
pandas = "^2.2.2"
patchify = "^0.2.3"
matplotlib = "^3.8.4"
networkx = "^3.3"
scikit-image = "^0.23.2"
skan = "^0.11.1"
numpy = "1.23.5"
pytest = "^8.2.0"
pytest-mock = "^3.14.0"
sphinx = "^7.3.7"
coverage = "^7.5.1"
sphinx_rtd_theme= "2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
