[build-system]
requires = [
    'beautifulsoup4>=4.12.3',
    'certifi>=2023.7.22',
    'matplotlib>=3.8.0',
    'MetaTrader5>=5.0.4288',
    'numpy>=1.26.4',
    'pandas>=2.2.2',
    'pandas_datareader>=0.10.0',
    'plotly>=5.18.0',
    'python_binance>=1.0.19',
    'pytz>=2023.3.post1',
    'Requests>=2.31.0',
    'scikit_learn>=1.3.2',
    'scipy>=1.13.0',
    'seaborn>=0.13.2',
    'setuptools>=69.0.2',
    'SQLAlchemy>=2.0.29',
    'urllib3>=2.2.1',
    'wbgapi>=1.0.12',
    'yfinance>=0.2.31'
]
build-backend = 'setuptools.build_meta'