[build-system]
requires = ["flit_core>=3.2"]
build-backend = "flit_core.buildapi"

[project]
name = "docmesh_agent"
description = "Agent helps you dig the paper connection!"
authors = [
    {name="Zhengkai Yang", email="kyle.yang1995@gmail.com"},
]
readme = "README.md"
dynamic = ["version"]
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent"
]
requires-python = ">=3.8"
dependencies = [
    "docmesh>=0.0.5",
    "langchain>=0.1.15",
    "langchain-openai>=0.1.3",
    "fastapi==0.111.0",
    "uvicorn==0.29.0",
    "gunicorn==19.3.0",
]

[tool.flake8]
max-line-length = 120
