[tool.poetry]
name = "malin"
version = "0.2.1"
description = ""
authors = ["Yassine Damiri <yassine.damiri@epita.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
