[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pisahkan-ktp"
version = "0.1.8"
authors = ["Hanif Yuli Abdillah P <hanifabd23@gmail.com>"]
description = "Python package for detecting entities in text based on a dictionary and fuzzy similarity"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = ">=3.7"
opencv-python = "4.8.0.76"
opencv-contrib-python = "4.9.0.80"
pythonRLSA = "1.0.0"

[tool.poetry.dev-dependencies]
