[build-system]
requires = ["poetry-core>=1.0.18"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "aipkgs-core"
version = "1.0.18"
description = "Core package for aipy packages."
authors = ["Alexy <alexy.ib@outlook.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://gitlab.com/aipy/public/packages.git"
repository = "https://gitlab.com/aipy/public/packages.git"
keywords = ["ai"]
include = [
    "LICENSE",
]
#packages = [
#    { include = "src" }
#]

#[tool.poetry.packages.two]
#name = "test"
#packages = [
#    { include = "test", from = "src" }
#]

#[tool.relaxed-poetry.sub-projects]
#sub-project-1 = 'path-to-sub-project-1'
#sub-project-2 = 'path-to-sub-project-2'

[tool.poetry.dependencies]
python = "^3.11.4"
requests = "^2.28.1"
pendulum = "^2.0.0"
email-validator = "^2.1.1"
emoji = "^2.11.1"
phonenumbers = "^8.13.36"
bcrypt = "^4.1.3"
flask-jwt-extended = "^4.6.0"
aipkgs-requests = "^1.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.1"

