# pyodide-mkdocs-theme
# Copyleft GNU GPLv3 üÑØ 2024 Fr√©d√©ric Zinelli
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.
# If not, see <https://www.gnu.org/licenses/>.

# Voici un exemple presque complet de configuration pour un fichier
# mkdocs.yml utilisant pyodide-mkdocs-theme.

site_url: "{>> L'adresse de votre site web ici <<}"
site_name: "{>> Titre pour votre site <<}"
# site_description: "(optionnel)"
# repo_url: "(optionnel)"
# edit_uri: "(optionnel)"

# Copyright "CC BY-NC-SA"
copyright: |
  <p xmlns:cc="http://creativecommons.org/ns#"
  xmlns:dct="http://purl.org/dc/terms/">Partage ou adaptation possible selon les conditions de la
  licence <a
  href="http://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1"
  target="_blank" rel="license noopener noreferrer"
  style="display:inline-block;"> CC BY-NC-SA 4.0 <img
  style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"
  src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img
  style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"
  src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"><img
  style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"
  src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1"><img
  style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"
  src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1"></a></p>


docs_dir: docs

nav:
  - "Accueil": index.md
# - ...

# Pour supprimer certains fichiers markdown de la navigation (pattern shell):
# not_in_nav: |
#   */**/*.md

# N√©cessite mkdocs 1.6+ pour fonctionner correctement. Sinon, vous pouvez utiliser
# le plugin mkdocs-exclude √† la place.
# Ne surtout pas mettre de commentaires sur la ligne d'exclusion des fichiers python... !
# (exclure les fichiers python n'affecte pas les "python_libs")
exclude_docs: |
  **/*_REM.md
  **/*.py

theme:
  name: pyodide-mkdocs-theme

# features:
#   - navigation.instant      # Ne surtout pas activer cette option !


# Configuration minimale pour les plugins
plugins:
  - awesome-pages:          # Pas indispensable, mais... (pip install mkdocs-awesome-pages-plugin)
      collapse_single_pages: true

  - material/search         # !!REQUIS!! / Nota: Les plugins de material-mkdocs doivent √™tre pr√©fix√©s!

  - pyodide_macros:         # !!REQUIS!!
      on_error_fail: true   # Fortement conseill√©...

# - exclude-search:         # APR√àS le plugin search (pip install mkdocs-exclude-search)
#     exclude:              # Pour les fichiers inclus dans le build, que la recherche ne doit pas indexer
#       - bac_a_sable.md


markdown_extensions:

  # Extensions indispensables pour le th√®me:
  - md_in_html              # !!REQUIS!!
  - admonition              # !!REQUIS!! Blocs color√©s:  !!! info "ma remarque"
  - attr_list               # !!REQUIS!! Un peu de CSS et des attributs HTML, ex: { #id .class style="display:none" }
  - pymdownx.details        # !!REQUIS!! Admonition: ??? -> peuvent se d√©plier ; ???+ -> peuvent se replier.
  - pymdownx.emoji:         # !!REQUIS!! √âmojis:  :boom: (utilis√© dans les terminaux)
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight      # !!REQUIS!! Coloration syntaxique du code
  - pymdownx.inlinehilite   # !!REQUIS!! Coloration syntaxique pour les "code spans": `#!python  code_python`
  - pymdownx.snippets:      # !!REQUIS!! Inclusion de fichiers externe.
      check_paths: true     # Fortement conseill√© !
  - pymdownx.superfences    # !!REQUIS!!
  - pymdownx.arithmatex:    # !!REQUIS!! Pour LaTex
      generic: true
  - pymdownx.striphtml:
      strip_js_on_attributes: false     # !!REQUIS!!
      strip_attributes: ""              # !!REQUIS!!


  # Extensions conseill√©es:
  - meta
  - abbr
  - def_list                # Les listes de d√©finition.
  - footnotes               # Notes[^1] de bas de page.  [^1]: ma note.
  - pymdownx.caret          # Passage ^^soulign√©^^ ou en ^exposant^.
  - pymdownx.mark           # Passage ==surlign√©==.
  - pymdownx.tilde          # Passage ~~barr√©~~ ou en ~indice~.
  - pymdownx.keys           # Touches du clavier:  ++ctrl+d++
  - pymdownx.tasklist:      # Cases √† cocher  - [ ]  et - [x]
      custom_checkbox: false
      clickable_checkbox: true
  - pymdownx.tabbed:        # Volets glissants:  === "Mon volet"
      alternate_style: true # Meilleure compatibilit√© pour mobiles
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  # - toc:
  #     toc_depth: 0        # Si vous voulez supprimer la ToC (table of content) de la page



# Si mkdocs est lanc√© en mode strict (mkdocs ... --strict), les warnings l√®veront une erreur
validation:
  omitted_files: warn
  unrecognized_links: warn
