[build-system]
requires = ["setuptools>=40.8.0","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jgtml"
version = "0.0.50"
authors = [
  { name="Guillaume Isabelle", email="jgi@jgwill.com" },
]

description = "JGT Ml - Machine Learning Tools"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
  'pandas>=0.25.1',
  'python-dotenv>=0.19.2',
  'jgtpy>=0.4.47',
  'matplotlib>=3.3.1',
  'plotly>=5.18.0',
  'mplfinance>=0.12.10b0',
  'scipy>=1.7.3',
  'panel>=1.2.3',
  'seaborn>=0.13.2', 
  'dash'
]	
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/jgwill/jgtml"
"Bug Tracker" = "https://github.com/jgwill/jgtml/issues"


