[tool.poetry]
name = "cdnmon"
version = "0.4.1"
description = ""
authors = ["Yihang Wang <wangyihanger@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"
coloredlogs = "^15.0.1"
pyyaml = "^6.0.1"
ipy = "^1.1"


[tool.poetry.group.dev.dependencies]
build = "^0.10.0"
twine = "^4.0.2"
deptry = "^0.16.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
